### ISSUE TITLE
RuntimeError: expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride=[1, 1, 1]

### ISSUE THREAD

**Issue by lxy51** [lartpang/mssim.pytorch#1]
RuntimeError: expected stride to be a single integer value or a list of 2 values to match the convolution dimensions, but got stride=[1, 1, 1]

**Comment by lartpang** [comment]
@lxy51 

Could you share the demo code?

**Comment by lxy51** [comment]
I think I know what the problem is. I'm using 3D data. Is there a 3D data version of this code?

**Comment by lxy51** [comment]
@lartpang

**Comment by lartpang** [comment]
@lxy51 

This requires adjusting the generation logic of the Gaussian kernel, as well as the function settings of the filtering process.
It will take a little time to tweak the code for compatibility.

**Comment by lxy51** [comment]
Ok, thank you. If you have time later, I hope you can implement a 3D data version. Thank you for your help

**Comment by lartpang** [comment]
@lxy51 

Okay, thanks for the advice.

**Comment by lartpang** [comment]
@lxy51 

In the latest commit, I refactored the code and updated SSIM with support for 1D, 2D and 3D data, and MS-SSIM with support for 2D and 3D data.For details on how to use it, you can refer to the code snippet in the test script:

https://github.com/lartpang/mssim.pytorch/blob/0513122ed8dc2987a71a51d3d97f0c8d4fb428c5/test/test_ssim.py#L43-L70

> [!note]
> One thing to note here is the `window_size` item. For 3D data with shape `B,C,T,H,W`, usually $T<<H,W$, so it is better to set `window_size` independently on the three dimensions.

**Comment by lxy51** [comment]
Thank you very much for your help
